### PR TITLE
Major upgrade

### PR DESCRIPTION
**Pull request by alertedsnake**
**Breaking changes**:

* Hipchat is no longer supported - it's dead, Jim.
* Removed command-line arguments `--lock` and `--state_path`

**New features:**

* Switched to using AsyncIO for fetching feed data
* Config files can now be YAML or JSON, split handling of such into its own python file, and now using **Box** to make working with config data easy
* A new locking framework was built, supporting both file locking (as previous), and using DynamoDB (for running in containers). This framework is extensible for other locking methods.
* A new storage framework was built, supporting both local files and DynamoDB.  This stores the date of the most recently processed messages, so as to not alert on messages already seen. This framework is extensible for other storage methods.
* Added a flag for feed groups to alert if fetching a feed fails
* Created a `Dockerfile` so you can containerize the thing, and a `docker-compose.yaml` for example purposes.  It makes some assumptions.

**Enhancements:**

* All dates in events will be formated RFC1123 style, in localtime (or  another TZ if set in the config file)
* Now doing case-insensitive parsing messages for keywords
* Logging now always adds the feed name to messages
* Config file option `loglevel` can be used to set the default, command-line will always override though.
* Split alerts into their own file, so it's easy to add more
* Most functions and classes documented
* Cleanly handling timeouts and fetch exceptions
* Actual executable is now a entrypoint (as defined in `setup.py`)
* Added additional message keywords for determining the message color
* Slack and DynamoDB support are now optional, use the extras with pip to install those dependencies

**To Do:**

* More documentation on the config file format and available options, and the way global->group merging works

OPS-7393

### CODE REVIEW

**Review by ksindi — APPROVED** [review]
Looks great!

**Comment by ksindi** [comment]
Only comment is I didn't see many tests

**Comment by alertedsnake** [comment]
Indeed, that ought to be on the todo list..... perhaps I'll start on that today.

**Comment by alertedsnake** [comment]
Hey, a neat thing just happened - I started writing tests and found a bug!

**Review by jw-travis — APPROVED** [review]

**Pull request merged**
